variables:
  project_path: './_dclone'

log_file: '/var/billy/depy.log'
stamp_path: '/var/billy/depy.stamp'

repository:
  force_rebuild: false
  init: true
  path: ${{ variables.project_path }}
  url: 'https://github.com/sidneydijkstra/Billy.git'
  branch: 'refactor'

stages:
  - build
  - test

jobs:
  build:
    steps:
      # Stop the service if it is running
      - service-stop: billy.service
      # Pull out the repository
      - pull
      # Create the service file
      - service-create:
          name: billy.service
          directory: /var/billy
          description: The Billy Discord bot
          command: /bin/bash ./startup.sh
      # Run the build command
      - run: |
          rm -r /var/billy
          cp -r ${{ variables.project_path }} /var/billy
      # Enable the service so it starts on boot
      - service-enable: billy.service
      # Start the service
      - service-start: billy.service
  test:
    steps:
      # Run tests using the specified test command
      - run: |
          echo "this is a test"

sleep_time: 30

mailer:
  enable: False
  url: 'smtp.example.com'
  user: 'user@example.com'
  password: 'password'
  to: 'recipient@example.com'
